kind: Workflow
metadata:
  generateName: hello-world-
spec:
  arguments:
    parameters:
    - name: name
      description: Name of the person to greet
      value: World

  artifactGC:
    forceFinalizerRemoval: true
  podGC:
    strategy: OnWorkflowSuccess

  entrypoint: main-workflow

  templates:

  #######################################################
  # Main workflow
  #######################################################
  - name: main-workflow
    steps:
    - - name: generate-greeting
        template: step1-script
        arguments:
          parameters:
          - name: name
            value: '{{workflow.parameters.name}}'
    - - name: summarize-greeting
        template: step2-container
        arguments:
          parameters:
          - name: greeting
            value: '{{steps.generate-greeting.outputs.parameters.greeting}}'

  #######################################################
  # Step 1: Script produces a greeting parameter
  #######################################################
  - name: step1-script
    inputs:
      parameters:
      - name: name
    outputs:
      parameters:
      - name: greeting
        valueFrom:
          path: /tmp/greeting.txt
    script:
      image: python:3.9
      command: ["python"]
      source: |
        name = "{{inputs.parameters.name}}"
        greeting = f"Hello, {name}!"
        
        # Write greeting to the parameter file
        with open("/tmp/greeting.txt", "w") as f:
            f.write(greeting)

  #######################################################
  # Step 2: Container reads greeting parameter
  #######################################################
  - name: step2-container
    inputs:
      parameters:
      - name: greeting  
    outputs:
      artifacts:
      - name: summary-file
        path: /tmp/summary.txt
        archive:
          none: {}
    container:
      name: summarize-container
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
      - |
        echo "Greeting: {{inputs.parameters.greeting}}" > /tmp/summary.txt
        echo "Saved summary to /tmp/summary.txt"
