# Generated by Django 5.0.11 on 2025-10-17 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyidentity',
            name='orcid',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('[0-9A-Z]{4}\\-[0-9A-Z]{4}\\-[0-9A-Z]{4}\\-[0-9A-Z]{4}', message='Enter a valid ORCID ID')]),
        ),
    ]
