# Generated by Django 5.2.8 on 2025-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apikeyidentity_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyidentity',
            name='id_type',
            field=models.CharField(choices=[('orcid', 'ORCID'), ('doi', 'DOI'), ('ror', 'ROR'), ('other', 'Other')], default='orcid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikeyidentity',
            name='identifier',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='apikeyidentity',
            name='orcid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
