# Generated by Django 5.2.8 on 2025-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251216_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyidentity',
            name='orcid',
            field=models.CharField(blank=True, help_text='DEPRECATED: use id_type + identifier instead', max_length=128, null=True),
        ),
    ]
